use eCom;

-- Which customers have placed more than 2 orders?
select Customers.customer_id, Customers.customer_Name, count(Orders.order_id) from Customers
JOIN Orders on Orders.customer_id = Customers.customer_id
group by Customers.customer_id, Customers.customer_Name
HAVING count(Orders.order_id) > 2;

-- What is the total revenue generated by each product category?
select Categories.category_Name,sum(OrderItems.quantity * Products.price) from OrderItems
JOIN Products on Products.product_id = OrderItems.product_id
JOIN Categories on Categories.category_id = Products.category_id
group by Categories.category_Name;

-- Which product generated the highest total revenue?
select p.product_Name, sum(oi.quantity * p.price) AS total_revenue from OrderItems oi
JOIN Products p ON p.product_id = oi.product_id
group by p.product_Name
ORDER BY total_revenue LIMIT 1;

-- List orders where the total quantity of items is greater than 5.
select order_id,sum(quantity) from OrderItems 
group by order_id
having sum(quantity) >= 5;

-- Find the top 5 products based on quantity sold.
select p.product_Name, sum(oi.quantity) AS total_quantity_sold from OrderItems oi
JOIN Products p ON p.product_id = oi.product_id
group by p.product_id , p.product_Name
order by total_quantity_sold DESC LIMIT  5;

-- Which customers have spent more than ₹500 in total?
select c.customer_Name, sum(amount) from Payments p
join Orders o on o.order_id = p.order_id
join Customers c on c.customer_id = o.customer_id
group by c.customer_Name
having sum(amount) > 500;

-- Find the total payment amount received per order.
select o.order_id ,sum(p.amount) from Payments p
JOIN Orders o ON o.order_id = p.order_id
group by o.order_id;

-- Which orders have not been paid yet?

-- List the customers who placed orders but haven't made any payment.
select c.customer_Name from Orders o
JOIN Customers c ON o.customer_id = c.customer_id
LEFT JOIN Payments p ON p.order_id = o.order_id
WHERE p.payment_id IS NULL; 

-- Identify the most frequently purchased product.
select p.product_Name, sum(o.quantity) AS total_quantity_sold from OrderItems o
JOIN Products p ON p.product_id = o.order_id
GROUP BY p.product_id, p.product_Name 
order by total_quantity_sold DESC;

-- What is the average amount spent per customer?
select avg(sum_amount) avg_spent_per_customer 
from(
	select c.customer_id, sum(p.amount) AS sum_amount from Payments p
	JOIN Orders o ON o.order_id = p.order_id
	JOIN Customers c ON c.customer_id = o.customer_id
	GROUP BY c.customer_id
) AS total;

-- Which product was never ordered?
select p.product_id, p.product_Name from Products p
LEFT JOIN OrderItems oi ON p.product_id = oi.product_id
WHERE oi.product_id is null;

-- Show the customer who placed the highest number of orders.
select customer_Name , count(o.order_id) AS total_order from Customers c
JOIN Orders o ON o.customer_id = c.customer_id
group by customer_Name;


-- Calculate the average quantity of items per order.
select avg(order_total_quantity) AS avg_quantity_per_order 
from(
	select oi.order_id, sum(oi.quantity) AS order_total_quantity
    from OrderItems oi
    group by oi.order_id 
) AS sub; 


-- Which categories have more than 3 products with price > ₹100?
select c.category_Name, count(p.product_id) AS product_Count from Products p
JOIN Categories c ON c.category_id = p.category_id
where(p.price) > 100
GROUP BY category_Name
having count(p.product_id) > 3;